apiVersion: v1
kind: Service
metadata:
  name: snake-game  # Changed from snake-game-service to snake-game
spec:
  type: LoadBalancer
  selector:
    app: snake-game
  ports:
    - port: 80
      targetPort: 80
